# Generated by Django 2.0.3 on 2018-04-14 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Port_desc',
            fields=[
                ('measurement', models.CharField(max_length=10)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
